# Generated by Django 2.1.8 on 2019-09-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190902_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractions_datail',
            options={'managed': True, 'verbose_name': '景点信息', 'verbose_name_plural': '景点详情信息'},
        ),
        migrations.AlterModelOptions(
            name='attractions_price',
            options={'managed': True, 'verbose_name': '景点门票价格', 'verbose_name_plural': '景点门票价格信息'},
        ),
        migrations.AlterModelOptions(
            name='banner_img',
            options={'managed': True, 'verbose_name': '轮播图', 'verbose_name_plural': '轮播图片信息'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'managed': True, 'verbose_name': '景点流量信息', 'verbose_name_plural': '景点流量详情信息'},
        ),
        migrations.AlterModelOptions(
            name='home_infor',
            options={'managed': True, 'verbose_name': '房间信息', 'verbose_name_plural': '房间详情信息'},
        ),
        migrations.AlterModelOptions(
            name='hotel_datail',
            options={'managed': True, 'verbose_name': '酒店详情', 'verbose_name_plural': '酒店详情信息'},
        ),
        migrations.AlterModelOptions(
            name='hotel_infor',
            options={'managed': True, 'verbose_name': '酒店房间信息', 'verbose_name_plural': '酒店房间信息'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True, 'verbose_name': '新闻', 'verbose_name_plural': '新闻详情信息'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'verbose_name': '订单信息', 'verbose_name_plural': '订单详情信息'},
        ),
    ]
