# Generated by Django 2.1.8 on 2019-09-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190902_1954'),
    ]

    operations = [
    ]
