# Generated by Django 2.1.8 on 2019-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190902_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionsDatail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='景点名称')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='景点地址')),
                ('datail', models.TextField(blank=True, null=True, verbose_name='景点详情')),
                ('suggest', models.IntegerField(blank=True, null=True, verbose_name='是否推荐')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='景点所在省 ')),
                ('area', models.CharField(blank=True, max_length=20, null=True, verbose_name='景点所在市')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='景点概要')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='景点类型')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='景点收益')),
                ('sum_order', models.IntegerField(blank=True, null=True, verbose_name='景点订单')),
                ('auth_user', models.IntegerField(blank=True, null=True, verbose_name='用户登录id')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '景点详情',
                'verbose_name_plural': '景点详情',
                'db_table': 'attractions_datail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttractionsImg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attractions_id', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='attractions/%d/')),
            ],
            options={
                'verbose_name': '景点图片',
                'verbose_name_plural': '景点图片',
                'db_table': 'attractions_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttractionsOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attractions_id', models.IntegerField(blank=True, null=True, verbose_name='景点id')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='订单价格')),
                ('auth_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('use_time', models.DateTimeField(blank=True, null=True, verbose_name='有效时间')),
            ],
            options={
                'verbose_name': '景区订单信息',
                'verbose_name_plural': '景区订单信息',
                'db_table': 'attractions_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttractionsPrice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_id', models.IntegerField(blank=True, null=True, verbose_name='对应景点id')),
                ('child_price', models.FloatField(blank=True, null=True, verbose_name='儿童价')),
                ('stu_price', models.FloatField(blank=True, null=True, verbose_name='学生价')),
                ('adult_price', models.FloatField(blank=True, null=True, verbose_name='成人价')),
            ],
            options={
                'verbose_name': '景点价格信息',
                'verbose_name_plural': '景点价格信息',
                'db_table': 'attractions_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('hotel_user', models.IntegerField(blank=True, null=True)),
                ('attractions_user', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeDatail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField(blank=True, null=True, verbose_name='对应酒店id')),
                ('home', models.CharField(blank=True, max_length=255, null=True, verbose_name='房型')),
                ('person_num', models.IntegerField(blank=True, null=True, verbose_name='可容纳人数')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='房价')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='剩余数量')),
                ('datail', models.TextField(blank=True, null=True, verbose_name='房型介绍')),
                ('clean', models.IntegerField(blank=True, null=True, verbose_name='是否打扫')),
                ('get_person', models.IntegerField(blank=True, null=True, verbose_name='是否有人')),
            ],
            options={
                'verbose_name': '房间详情',
                'verbose_name_plural': '房间详情',
                'db_table': 'home_datail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelDatail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='店长')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='酒店名称')),
                ('max_price', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('min_price', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('datail', models.TextField(blank=True, null=True, verbose_name='酒店介绍')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='酒店地址')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='酒店电话')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='收益')),
                ('sum_order', models.IntegerField(blank=True, null=True, verbose_name='订单总量')),
                ('home_num', models.IntegerField(blank=True, null=True, verbose_name='房间总数')),
                ('in_time', models.TimeField(blank=True, null=True, verbose_name='营业时间')),
                ('auth_user', models.IntegerField(blank=True, null=True, verbose_name='登录用户id')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name': '酒店详情',
                'verbose_name_plural': '酒店详情',
                'db_table': 'hotel_datail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelImg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_id', models.IntegerField(blank=True, null=True)),
                ('hotel_id', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='hotel/%n/%m/')),
            ],
            options={
                'verbose_name': '酒店图片',
                'verbose_name_plural': '酒店图片',
                'db_table': 'hotel_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('auth_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('hotel_id', models.IntegerField(blank=True, null=True, verbose_name='酒店id')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='订单价格')),
                ('use_time', models.DateTimeField(blank=True, null=True, verbose_name='有效时间')),
            ],
            options={
                'verbose_name': '酒店订单信息',
                'verbose_name_plural': '酒店订单信息',
                'db_table': 'hotel_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField(blank=True, null=True, verbose_name='酒店id')),
                ('home', models.CharField(blank=True, max_length=255, null=True, verbose_name='房型')),
                ('attractions_id', models.IntegerField(blank=True, null=True, verbose_name='景点id')),
                ('attractions_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='景点门票名称')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='订单价格')),
                ('auth_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('use_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
            ],
            options={
                'verbose_name': '用户订单',
                'verbose_name_plural': '用户订单',
                'db_table': 'user_order',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'managed': False, 'verbose_name': '流量分析', 'verbose_name_plural': '流量分析'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False, 'verbose_name': '新闻详情', 'verbose_name_plural': '新闻详情'},
        ),
        migrations.AlterModelTable(
            name='flow',
            table='flow',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
